### ISSUE TITLE
Trying to connect to named Exchange

### ISSUE THREAD

**Issue by random0000** [brandonhamilton/bunyan-logstash-amqp#2]
I am able to connect to RabbitMQ when I just use rountingKey but when I try to specify the Exchange it doesn't connect.  I'm new to Node/JS so I am not sure of the exact error being thrown.
This works:
exchange: {
                routingKey: 'MyLogs'
            }

This does not:
exchange: {
                name: 'MyExchange',
                routingKey: 'MyLogs'
              }

Also, do you have an example of setting the exchange properties?

Thanks!

**Comment by random0000** [comment]
Just an update on this... in the node amqp exchange.js code there is a field called auto_delete (note the "_").  Later on there is a check in serializer.js that compares the fields with args passed in.  If the strict flag is true (which it is in this case) then it tries to find autoDelete in args which only has auto_Delete in it.  This is regardless of whether or not the field is specified in the exchange properties field.

So I guess this might be an amqp issue.

**Comment by cp2587** [comment]
I have the exact same problem. Did you manage to find a workaround ?

**Comment by brandonhamilton** [comment]
Does this issue still occur on 1.0.7, which has updated the dependency to amqp@0.2.6 ?

An example of using the exchange properties:

```
exchange: {
    name: 'logs',
    routingKey: 'api',
    properties: { 
        durable: true,
        type: 'topic', 
        autoDelete: false
    }
}
```
